version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: oauth_postgres
    environment:
      POSTGRES_USER: oauth_user
      POSTGRES_PASSWORD: oauth_password
      POSTGRES_DB: oauth_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - oauth_network

volumes:
  postgres_data:

networks:
  oauth_network:
